spring.application.name=schoolsystem-backend
server.port=8080

# MySQL permanent database (stored on disk in MySQL Server data directory)
spring.datasource.url=jdbc:mysql://localhost:3306/schoolsystem_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Kunal@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
